kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx16G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true

kotlin.native.disableCompilerDaemon = true

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897