[versions]
agp = "8.2.0"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.6.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
compose-plugin = "1.6.11"
junit = "4.13.2"
kotlin = "2.0.0"
ktorVersion = "3.0.0-beta-1"
viewmodelVersion = "2.8.0"
kotlinSerializationVersion = "1.7.1"
uiToolingPreviewAndroid = "1.6.8"
skikoVersion = "0.8.9"
voyagerVersion = "1.1.0-beta02"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
ktor = {module = "io.ktor:ktor-client-core", version.ref="ktorVersion"}
ktorCio = {module = "io.ktor:ktor-client-cio", version.ref="ktorVersion"}
viewmodel = {module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref="viewmodelVersion"}
kotlinSerialization = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="kotlinSerializationVersion"}
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }

voyagerNavigator = {module = "cafe.adriel.voyager:voyager-navigator", version.ref="voyagerVersion"}
voyagerScreenModel = {module = "cafe.adriel.voyager:voyager-screenmodel", version.ref="voyagerVersion"}
voyagerTransitions = {module = "cafe.adriel.voyager:voyager-transitions", version.ref="voyagerVersion"}
voyagerLifecycleKmp = {module = "cafe.adriel.voyager:voyager-lifecycle-kmp", version.ref="voyagerVersion"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = {id = "plugin.serialization", version.ref = "kotlin"}